<img src="https://udemedellin.edu.co/wp-content/uploads/2022/10/logo_udemedellin2.png" width="30%">

**ESPECIALIZACIÓN EN CIENCIA DE DATOS E INTELIGENCIA ARTIFICIAL**

*INTRODUCCION A LA CIENCIA DE DATOS*<br>

DOCENTE:<br>
Mateo Cano Solis<br>

NOMBRES:
1. Santiago Casatñeda Garcia
2. Andres Eduardo Medina
3. David Alejandro Montilla Orjuela



Abril 2026


---

# **"Análisis Predictivo y Caracterización de la Contratación Estatal en Colombia: Un Enfoque Basado en Datos de SECOP I y II"**

## **1. introducción:**
La contratación pública en Colombia representa uno de los pilares más importantes para el desarrollo socioeconómico del país. Con la transición y coexistencia de las plataformas SECOP I y SECOP II, se ha generado un volumen de información sin precedentes sobre cómo el Estado invierte sus recursos. Sin embargo, la complejidad y diversidad de estos datos exigen el uso de herramientas avanzadas de Analítica de Datos para transformar registros administrativos en conocimiento estratégico.

Este proyecto se enfoca en el estudio de los procesos de compra pública que han culminado en contratos efectivos. A través de técnicas de Aprendizaje Automático (Machine Learning), se busca descubrir patrones ocultos en las modalidades de selección, los tiempos de ejecución y la distribución de los presupuestos, permitiendo una visión técnica que aporte a la transparencia y a la eficiencia en la gestión pública

<br><br>

## **2. Objetivos:**

Objetivo General
Desarrollar un modelo de análisis basado en técnicas de aprendizaje automático para caracterizar y predecir métricas clave en los procesos de contratación estatal integrados en las plataformas SECOP I y II.

Objetivos Específicos
Realizar un Análisis Exploratorio de Datos (EDA) para identificar las tendencias de contratación por sectores, regiones y modalidades de selección.

Procesar y estandarizar la información integrada de SECOP I y II, gestionando la limpieza de datos faltantes y la codificación de variables categóricas.

Evaluar diferentes arquitecturas de modelos predictivos mediante el uso de herramientas de AutoML (como AutoGluon), con el fin de determinar el algoritmo que ofrezca mayor precisión en la clasificación o estimación de resultados contractuales.

Interpretar los resultados obtenidos para identificar qué variables (como cuantía, ubicación o tipo de entidad) tienen mayor peso en la configuración de un contrato exitoso.

<br>
VARIABLES OBSERVADAS
<br><br>

|Num|Nombre de la columna|Descripción|Nombre del campo API|Tipo de dato|
|-|-|-|-|-|
|1|Nivel Entidad|Nivel de la entidad publica que desarrolla el proceso de compra, de acuerdo a su cobertura|Nivel entidad|Texto|
|2|Código Entidad SECOP|Código de la entidad en la plataforma SEECOP|Código_entidad_en_secop|Texto |
|3|Nombre de la Entidad|Nombre de la Entidad que desarrolla el proceso de compra pública|nombre_de_la_entidad|Texto |
|4|NIT de la Entidad|	Identificador de la Entidad que desarrolla el proceso de compra pública|nit_de_la_entidad|	Texto|
|5|Departamento Entidad|	Departamento de origen de la Entidad en la plataforma SECOP|	departamento_entidad|	Texto|
|6|Municipio Entidad|	Municipio de origen de la Entidad en la plataforma SECOP|	municipio_entidad|	Texto|
|7|Estado del Proces|	Estado del proceso, de acuerdo con el flujo que se establece y a la modalidad de adquisición bajo la cual se desarrolla|	estado_del_proceso|	Texto|
|8|Modalidad de Contratación|	Modo de adquisición, de acuerdo con las características del proceso y del producto o servicio involucrados|	modalidad_de_contrataci_n|	Texto|
|9|Objeto del contrato|	Descripción detallada del producto o servicio a adquirir, definida al momento de redactar el contrato|	objeto_a_contratar|	Texto|
|10|Objeto del proceso|	Objeto de contratación registrado en la fase de publicación del proceso|	objeto_del_proceso|	Texto|
|11|Tipo de Contrato|	Tipo de contrato que se firma al finalizar el proceso de compra pública|	tipo_de_contrato|	Texto|
|12|Fecha de Firma del Contrato|	Fecha en que se firmó el contrato, sea de forma física o digital|	fecha_de_firma_del_contrato|	Marca de tiempo variable|
|13|Fecha inicio ejecución|	Fecha de Inicio de Ejecución del Contrato|	fecha_inicio_ejecuci_n|	Marca de tiempo variable|
|14|Fecha fin ejecución|	Fecha definida en el contrato como la fecha de finalización de la ejecución|	fecha_fin_ejecuci_n|	Marca de tiempo variable|
|15|ID Contrato|	Identificador en la plataforma del contrato firmado|	numero_del_contrato|	Texto|
|16|ID Proceso|	identificador en la plataforma del proceso desarrollado|	numero_de_proceso|	Texto|
|17|Valor Contrato|	Valor del contrato firmado|	valor_contrato	|numerica|
|18|Núm Raz Social Contratista|Nombre del contratista o de la empresa que proveerá los productos o servicios relacionados en el proceso de compra|num_raz_social_contratista|Texto|
|19|	URL Contrato|	URL del proceso en su correspondiente plataforma.|	url_contrato|	Texto|
|20	|Origen	|Plataforma Origen a donde pertenecen los datos|	origen	|Texto|
|21	|Tipo Documento Proveedor	|Corresponde al tipo de documento del proveedor	|tipo_documento_proveedor|	Texto|
|22|	Documento Proveedor	|Corresponde al número de documento del proveedor|	documento_proveedor	|Texto|

## **Carga de Datos:**

In [4]:
#Importacion de librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#import seaborn as sns
import math
#import scipy.stats as stats
#import statsmodels.api as sm
#import statsmodels.formula.api as smf
#import os
#from scipy.stats import chi2_contingency, pearsonr, kruskal

# Cargar el dataset optimizado
df = pd.read_parquet('datos_secop.parquet')

#visualizar todo el df en pantalla
pd.set_option('display.max_columns', None)

# generar variable para conteo final de Nas
filas_iniciales = len(df)

#numero de columnas y filas
print(f"El dataset tiene: {df.shape[0]} filas y {df.shape[1]} columnas")

El dataset tiene: 300000 filas y 22 columnas

## **Visualizar el df**

In [5]:
# Mostrar  5 filas aleatorias
df_aleatorio = df.sample(5)
df_aleatorio

,nivel_entidad,codigo_entidad_en_secop,nombre_de_la_entidad,nit_de_la_entidad,departamento_entidad,municipio_entidad,estado_del_proceso,modalidad_de_contrataci_n,objeto_a_contratar,objeto_del_proceso,tipo_de_contrato,fecha_de_firma_del_contrato,fecha_inicio_ejecuci_n,fecha_fin_ejecuci_n,numero_del_contrato,numero_de_proceso,valor_contrato,nom_raz_social_contratista,url_contrato,origen,tipo_documento_proveedor,documento_proveedor
287738,Nacional,702066127,IDARTES,900413030,Distrito Capital de Bogotá,Bogotá,Aprobado,Contratación directa,Prestar servicios de apoyo a la gestión al Ins...,Prestar servicios de apoyo a la gestión al Ins...,Prestación de servicios,2025-11-27T00:00:00.000,None,2026-03-15T00:00:00.000,CO1.PCCNTR.8642330,2256-2025,12250000,Enny Farley Cortes Zambrano,https://community.secop.gov.co/Public/Tenderin...,SECOPII,Cédula de Ciudadanía,1104708047
206045,Territorial,710593401,ALCALDIA DE SANTO TOMAS ATLANTICO,800116284,Atlántico,Santo Tomás,En ejecución,Contratación directa,PRESTACION DE SERVICIOS DE APOYO A LA GESTION ...,PRESTACION DE SERVICIOS DE APOYO A LA GESTION ...,Prestación de servicios,2025-11-14T00:00:00.000,2025-11-14T00:00:00.000,2025-12-28T00:00:00.000,CO1.PCCNTR.8547971,PS- 318/025 ST,3300000,Jaismila Charris Cervantes,https://community.secop.gov.co/Public/Tenderin...,SECOPII,Cédula de Ciudadanía,22623721
256505,Territorial,718586266,EMPRESA REGIONAL AGUAS DEL TEQUENDAMA S.A. E.S.P.,900126313,No Definido,No Definido,Modificado,Contratación régimen especial,PRESTAR APOYO COMO RELEVADOR DE TURNOS DE LOS ...,PRESTAR APOYO COMO RELEVADOR DE TURNOS DE LOS ...,Prestación de servicios,2025-07-09T00:00:00.000,2025-07-09T00:00:00.000,2025-11-30T00:00:00.000,CO1.PCCNTR.8065176,OPS-135/2025,11932305,Jhonatan Sebastián Gil silva,https://community.secop.gov.co/Public/Tenderin...,SECOPII,Cédula de Ciudadanía,1072427221
154186,Territorial,702158254,MUNICIPIO DE SOACHA..,800094755,Cundinamarca,Soacha,Modificado,Contratación directa,PRESTACIÓN DE SERVICIOS PROFESIONALES PARA EL ...,PRESTACIÓN DE SERVICIOS PROFESIONALES PARA EL ...,Prestación de servicios,2025-01-07T00:00:00.000,2025-01-08T00:00:00.000,2025-11-07T00:00:00.000,CO1.PCCNTR.7203538,0209-2025,44713333,jimmy orlando sabogal perozo,https://community.secop.gov.co/Public/Tenderin...,SECOPII,Cédula de Ciudadanía,80240173
46413,Territorial,701695108,POLICIA METROPOLITANA DE POPAYAN,900593683,Cauca,No Definido,Borrador,Contratación directa,NO DEFINIDO,Sin Descripcion,Prestación de servicios,None,None,None,CO1.PCCNTR.1578809,CO1.PCCNTR.1578809,0,NO DEFINIDO,https://community.secop.gov.co/Public/Tenderin...,SECOPII,Sin Descripcion,No Definido

OBSERVACION: Existen en la columna contratos que estan en estado borrador lo cual es que aun no está publicado oficialmente o no ha sido adjudicado o está en proceso de elaboración o revisión, por lo que carece de mucha de informacion, estas filas con este valor son candidatas a eliminar

## **Tratamiento preliminar de datos**

In [6]:
# Obtener un resumen de la estructura del conjunto de datos:

print("\n-------TABLA CON TIPO DE VARIABLE VALORES UNICOS Y VALORES FALTANTES-------\n")
def generar_diccionario(Data):
    dicc = []
    for col in Data.columns:
        dicc.append({
            "Variable": col,
            "Tipo pandas": Data[col].dtype,
            "Cantidad de valores únicos": Data[col].nunique(),
            "Valores faltantes": Data[col].isna().sum()
        })
    return pd.DataFrame(dicc)

generar_diccionario(df)

-------TABLA CON TIPO DE VARIABLE VALORES UNICOS Y VALORES FALTANTES-------

,Variable,Tipo pandas,Cantidad de valores únicos,Valores faltantes
0,nivel_entidad,object,7,0
1,codigo_entidad_en_secop,object,5103,0
2,nombre_de_la_entidad,object,5239,0
3,nit_de_la_entidad,object,4200,0
4,departamento_entidad,object,38,0
5,municipio_entidad,object,1079,0
6,estado_del_proceso,object,19,0
7,modalidad_de_contrataci_n,object,31,0
8,objeto_a_contratar,object,165211,0
9,objeto_del_proceso,object,172952,1
10,tipo_de_contrato,object,33,0
11,fecha_de_firma_del_contrato,object,2474,60978
12,fecha_inicio_ejecuci_n,object,2898,101564
13,fecha_fin_ejecuci_n,object,3983,48443
14,numero_del_contrato,object,281426,0
15,numero_de_proceso,object,243422,81
16,valor_contrato,int64,105657,0
17,nom_raz_social_contratista,object,193061,2
18,url_contrato,object,250909,0
19,origen,object,2,0
20,tipo_documento_proveedor,object,18,0
21,documento_proveedor,object,190072,5

##OBSERVACION:
De la anterior tabla podemos ver los siguientes problemas en el dataset: <br>
-

Eliminar valores son esado borrador en la columna estado_del_proceso

#debemos tenr metricas de calsificacion y variar el treshold